In [7]:
import numpy as np
import math
import torch as t
import torch.nn as nn
import torch.nn.functional as F
from torch.autograd import Variable as V


HIDDEN1_UNITS = 300
HIDDEN2_UNITS = 600

class ActorNetwork(nn.Module):
    def __init__(self, state_size):
        super(ActorNetwork, self).__init__()
        self.fc1 = nn.Linear(state_size, HIDDEN1_UNITS)
        self.fc2 = nn.Linear(HIDDEN1_UNITS, HIDDEN2_UNITS)
        self.steering = nn.Linear(HIDDEN2_UNITS, 1)
        self.acceleration = nn.Linear(HIDDEN2_UNITS, 1)
        self.brake = nn.Linear(HIDDEN2_UNITS, 1)


    def forward(self, x):
        x = F.relu(self.fc1(x))
        x = F.relu(self.fc2(x))
        out1 = t.tanh(self.steering(x))
        out2 = t.sigmoid(self.acceleration(x))
        out3 = t.sigmoid(self.brake(x))
        out = t.cat((out1, out2, out3), 1) 
        return out
    
actor = ActorNetwork(10)
actor2 = ActorNetwork(10)


In [15]:
import collections
new_actor_state_dict = collections.OrderedDict()
print(actor.state_dict()['fc1.weight'])
for var_name in actor.state_dict():
    print(var_name)
    new_actor_state_dict[var_name]=actor.state_dict()[var_name]+actor2.state_dict()[var_name]
actor.load_state_dict(new_actor_state_dict)
print(actor.state_dict()['fc1.weight'])

tensor([[-0.9183, -0.4509, -0.6074,  ...,  0.5601, -1.0633, -1.1454],
        [ 1.1860, -0.4307, -0.3677,  ..., -0.2421,  0.2936, -0.5010],
        [ 0.4454,  1.1246,  0.8583,  ..., -0.5812,  0.0857, -0.0927],
        ...,
        [ 0.4865,  0.7845, -0.8035,  ..., -0.9653, -1.1573,  0.0869],
        [-0.5103, -0.1713, -1.4410,  ..., -0.4401,  0.4225, -0.0060],
        [-1.1258,  0.0342,  1.0124,  ...,  1.1164,  0.7491, -0.6355]])
fc1.weight
fc1.bias
fc2.weight
fc2.bias
steering.weight
steering.bias
acceleration.weight
acceleration.bias
brake.weight
brake.bias
tensor([[-1.1547, -0.6094, -0.8215,  ...,  0.6883, -1.2531, -1.4592],
        [ 1.4354, -0.5741, -0.5364,  ..., -0.2662,  0.3693, -0.5721],
        [ 0.5233,  1.3772,  1.0490,  ..., -0.7111,  0.0681, -0.0543],
        ...,
        [ 0.6225,  0.9733, -1.0278,  ..., -1.2001, -1.3987,  0.0934],
        [-0.6867, -0.1837, -1.7532,  ..., -0.5325,  0.5758, -0.0222],
        [-1.3314,  0.0659,  1.2668,  ...,  1.3981,  0.9223, -0.7171]])


In [33]:
input = []
for i in range(5):
    input.append(np.ones(10))
input = t.tensor(input).float()
print(input.size())
input

torch.Size([5, 10])


tensor([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [34]:
output = actor(input)
output.data

tensor([[0.0426, 0.4669, 0.4985],
        [0.0426, 0.4669, 0.4985],
        [0.0426, 0.4669, 0.4985],
        [0.0426, 0.4669, 0.4985],
        [0.0426, 0.4669, 0.4985]])

In [9]:
a = output.data.numpy()
a[0]

0.021801217

In [18]:
x = np.ones(10)
print(x.shape[0])
print(x.shape)
y = x.reshape(1, x.shape[0])
y

10
(10,)


array([[1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]])

In [20]:
x = np.asarray([i for i in range(10)])